language: python
env:
  global:
  - PROJECT_NAME=pareidolia
  - GITHUB_REPO_NAME=cmdoret/pareidolia
matrix:
  include:
  - python: '3.6'
  - python: '3.7'
    dist: xenial
    sudo: true
os:
- linux
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels bioconda
- conda update -q conda
- conda info -a
- conda create -c conda-forge -q -n test-environment python="$TRAVIS_PYTHON_VERSION"  pytest  pytest-cov  pylint  codecov  cooler
- pip install -v -Ur requirements.txt
- pip install -e .
script:
- pytest --pylint --pylint-error-types=EF --pylint-rcfile=.pylintrc pareidolia
- pytest --cov=pareidolia
after_success:
- codecov
